obstacle_range: 2.0
raytrace_range: 2.5
footprint: [[0.15, 0.25], [0.15, -0.25], [-0.56, -0.25], [-0.56, 0.25]]
inflation_radius: 0.6
cost_scaling_factor: 1.0
#transform_tolerance : 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: xv11, data_type: LaserScan, topic: /xv11_scan, marking: true, clearing: true, expected_update_rate: 0.4, inf_is_valid: true}
