local_costmap:
  global_frame: /odom
  robot_base_frame: /base_footprint
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  #publish_cost_grid: true
  #ORIG  inflation_radius: 1.5
  #ORIG  cost_scaling_factor: 2.0
  #inflation_radius: 1.5
  #cost_scaling_factor: 2.0
  transform_tolerance: 0.5
